name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential cmake

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests (optional)
        run: |
          if [ -f build/test ]; then
            ./build/test
          fi
